package com.stefanny.pokemon.model

object PokemonData {
    val pokemon = listOf(
        Pokemon(1,
            "Bulbaur",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
            "Grass, Poison",
            "Seed Pokémon",
            "0.7m (2′04″)",
            "6.9kg (15.2lbs)",
            "Overgrow"
        ),
        Pokemon(2,
            "Ivysaur",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
            "Grass, Poison",
            "Seed Pokémon",
            "1.0m (3′03″)",
            "13kg (28.7lbs)",
            "Overgrow"
        ),
        Pokemon(3,
            "Venosaur",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
            "Grass, Poison",
            "Seed Pokémon",
            "2m (6′07″)",
            "100kg (220.5lbs)",
            "Overgrow"
        ),
        Pokemon(4,
            "Charmander",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
            "Fire",
            "Lizard Pokémon",
            "0.6m (2′00″)",
            "8.5kg (18,7lbs)",
            "Blaze"
        ),
        Pokemon(5,
            "Charmeleon",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
            "Fire",
            "Flame Pokémon",
            "1.1m (3′07″)",
            "8.5kg (18,7lbs)",
            "Blaze"
        ),
        Pokemon(6,
            "Charizard",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
            "Fire, Flying",
            "Flame Pokémon",
            "1.7m (5′07″)",
            "90.5kg (199.5lbs)",
            "Blaze"
        ),
        Pokemon(7,
            "Squirtle",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
            "Water",
            "Tiny Turtle Pokémon",
            "0.5m (1′08″)",
            "9.0kg (19.8lbs)",
            "Torrent"
        ),
        Pokemon(8,
            "Wartortle",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
            "Water",
            "Turtle Pokémon",
            "1.0m (3′03″)",
            "22.5kg (49.6lbs)",
            "Torrent"
        ),
        Pokemon(9,
            "Blastoise",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
            "Water",
            "Shellfish Pokémon",
            "1.6m (5′03″)",
            "85.5kg (188.5lbs)",
            "Torrent"
        ),
        Pokemon(10,
            "Caterpie",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
            "Bug",
            "Worm Pokémon",
            "0.3m (1′00″)",
            "2.9kg (6.4lbs)",
            "Shield Dust"
        ),
        Pokemon(11,
            "Metapod",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
            "Bug",
            "Cocoon Pokémon",
            "0.7m (2′04″)",
            "9.9kg (21.8lbs)",
            "Shed Skin"
        ),
        Pokemon(12,
            "Butterfree",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
            "Bug, Flying",
            "Butterfly Pokémon",
            "1.1m (3′07″)",
            "32.0kg (70.5lbs)",
            "Compound Eyes"
        ),
        Pokemon(13,
            "Weedle",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
            "Bug, Poison",
            "Hairy Bug Pokémon",
            "0.3m (1′00″)",
            "3.2kg (7.1lbs)",
            "Shield Dust"
        ),
        Pokemon(14,
            "Kakuna",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
            "Bug, Poison",
            "Cocoon Pokémon",
            "0.6m (2′00″)",
            "10.0kg (22.0lbs)",
            "Shed Skin"
        ),
        Pokemon(15,
            "Beedrill",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
            "Bug, Poison",
            "Poison Bee Pokémon",
            "1.0m (3′03″)",
            "29.5kg (65.0lbs)",
            "Swarm"
        ),
        Pokemon(16,
            "Pidgey",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
            "Normal, Flying",
            "Tiny Bird Pokémon",
            "0.3m (1′00″)",
            "1.8kg (4.0 lbs)",
            "Keen Eye, Tangled Feet"
        ),
        Pokemon(17,
            "Pidgeotto",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
            "Normal, Flying",
            "Bird Pokémon",
            "1.1m (3′07″)",
            "30.0kg (66.1lbs)",
            "Keen Eye, Tangled Feet"
        ),
        Pokemon(18,
            "Pidgeot",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
            "Normal, Flying",
            "Bird Pokémon",
            "1.5m (4′11″)",
            "39.5kg (87.1lbs)",
            "Keen Eye, Tangled Feet"
        ),
        Pokemon(19,
            "Rattata",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
            "Normal",
            "Mouse Pokémon",
            "0.3m (1′00″)",
            "3.5kg (7.7 lbs)",
            "Run Away, Guts"
        ),
        Pokemon(20,
            "Raticate",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
            "Normal",
            "Mouse Pokémon",
            "0.7m (2′04″)",
            "18.5kg (40.8lbs)",
            "Run Away, Guts"
        ),
        Pokemon(21,
            "Spearow",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
            "Normal, Flying",
            "Tiny Bird Pokémon",
            "0.3m (1′00″)",
            "2.0kg (4.4 lbs)",
            "Keen Eye"
        ),
        Pokemon(22,
            "Fearow",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
            "Normal, Flying",
            "Beak Pokémon",
            "1.2m (3′11″)",
            "38.0kg (83.8 lbs)",
            "Keen Eye"
        ),
        Pokemon(23,
            "Ekans",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
            "Poison",
            "Snake Pokémon",
            "2.0m (6′07″)",
            "6.9kg (15.2 lbs)",
            "Intimidate, Shed Skin"
        ),
        Pokemon(24,
            "Arbok",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
            "Poison",
            "Cobra Pokémon",
            "3.5m (11′06″)",
            "65.0kg (143.3 lbs)",
            "Intimidate, Shed Skin"
        ),
        Pokemon(25,
            "Pikachu",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
            "Electric",
            "Mouse Pokémon",
            "0.4m (1′04″)",
            "6.0kg (13.2 lbs)",
            "Static"
        ),
        Pokemon(26,
            "Raichu",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
            "Electric",
            "Mouse Pokémon",
            "0.8m (2′07″)",
            "30.0kg (66.1 lbs)",
            "Static"
        ),
        Pokemon(27,
            "Sandshrew",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
            "Ground",
            "Mouse Pokémon",
            "0.6m (2′00″)",
            "12.0kg (26.5 lbs)",
            "Sand Viel"
        ),
        Pokemon(28,
            "Sandslash",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png",
            "Ground",
            "Mouse Pokémon",
            "1.0m (3′03″)",
            "29.5kg (65.0 lbs)",
            "Sand Viel"
        ),
        Pokemon(29,
            "Nidoran",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png",
            "Poison",
            "Poison Pin Pokémon",
            "0.4m (1′04″)",
            "7.0kg (15.4 lbs)",
            "Poison Point, Rivalry"
        ),
        Pokemon(30,
            "Nidorina",
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png",
            "Poison",
            "Poison Pin Pokémon",
            "0.8 m (2′07″)",
            "20.0 kg (44.1 lbs)",
            "Poison Point, Rivalry"
        )
    )
}